### ISSUE TITLE
Chrome - broken addon

### ISSUE THREAD

**Issue by lenisko** [kubuzetto/behind#1]
Hey there!

Add-on for Chrome errors with message `Can't decode photo "icon.svg"`

Chrome version: **83.0.4103.116 (latest)**
Add-on version: **0.2.1**

Screen
![abc](https://user-images.githubusercontent.com/10072920/86538662-7bb6d280-bef7-11ea-9d4f-f368891bcea5.png)

Aside that, thanks for add-on - it's working great on Firefox 👍

**Comment by kubuzetto** [comment]
Thank you very much for the issue!

The vector icon is what's causing the problem in Chrome, for some reason. Unfortunately I was made aware of the issue right after uploading 0.2.2 -- which is pending review right now. I cannot withdraw the review request in Chrome Web Store, or upload a new version; so I'll have to wait until somebody in Google rejects 0.2.2. After that I'll upload the working version.

**Comment by kubuzetto** [comment]
I uploaded 0.2.3 to the chrome web store. Now we wait :)

**Comment by kubuzetto** [comment]
CWS approved version 0.2.4. Closing the issue
