### ISSUE TITLE
No more works on Instagram

### ISSUE THREAD

**Issue by happysurf** [kubuzetto/behind#10]
From today seems that" behind" no more works on Instagram images, the result is a page with the list of images with the frame blank.
Firefox 89 beta.

**Comment by kubuzetto** [comment]
I couldn't come up with a reason for this. Scripts seem to work fine; the request seems successful but returns 0 bytes. I'll keep looking into it; it may have something to do with browser security.

For now, right-clicking on the blank frame in the preview page and selecting "View Image" seems to show the image.

**Comment by happysurf** [comment]
I tried also on a old Firefox 77 version but the problem is the same, maybe Instagram has changed something....

**Comment by Aspartaco** [comment]
May be a referer thing. Using the Smart Referer extension is also breaking the site since very recently.

**Comment by kubuzetto** [comment]
I just released a new minor version (0.2.13) that -hopefully- solves this issue. Retrieving the image data is not a bit more convoluted, but I tried it on Instagram and the images are shown properly. Closing the issue; but let me know if the problem persists. Thanks again for the bug report!

**Comment by vigilantesculpting** [comment]
Hi! I'm using Firefox 92.0, 64-bit on mac, with behind! v. 0.2.15.
It is not working very reliably on instagram for me. What I mean is, when I open up IG and use behind! the first time, everything seems to work, and I can see all images under the cursor, open them and save them.
But attempts after that fail - the behind! page shows up, but there are no images, not even empty frames.

If there is any testing or more info you require to bug fix this, please let me know.

**Comment by kubuzetto** [comment]
Thanks for the bug report @vigilantesculpting! I'm reopening the issue.

**Comment by kubuzetto** [comment]
Hi again @vigilantesculpting, I cannot seem to replicate this issue. Tried it with https://www.instagram.com/natgeo/; consecutive attempts seem to work as well. If you could describe the steps for the bug on a public page; I'm happy to look further into it.
