### ISSUE TITLE
↔, ↕ and ⤧ should, perhaps, not be displayed if there's only one image

### ISSUE THREAD

**Issue by lkintact** [kubuzetto/behind#14]
Also, the meaning of the symbols should probably be explained somewhere (I stumbled upon https://github.com/kubuzetto/behind/issues/9#issuecomment-727282008 by pure chance). Perhaps, `Ctrl+Shift+A -> Extensions -> behind! -> Details` is a fitting place?

Behind! version: 0.2.14,
Browser: Firefox 88.0.1.

**Comment by kubuzetto** [comment]
Solid suggestions, thank you! I'll definitely look into these soon.

**Comment by kubuzetto** [comment]
Thank you for the feedback! Added with 0.2.15
