### ISSUE TITLE
Feature suggestion: displaying image sizes

### ISSUE THREAD

**Issue by lkintact** [kubuzetto/behind#15]
Thank you for implementing #13.
What would you say about adding the file size to the image description, too? 

Behind! version: 0.2.15,
Browser: Firefox 88.0.1.

**Comment by jscher2000** [comment]
Maybe something like this around line 67 of inline.js:

    if (window.performance){
      var imgp = performance.getEntriesByName(im.src);
      if (imgp[0] && imgp[0].decodedBodySize > 0){
        spn.innerText += ' (' + imgp[0].decodedBodySize.toLocaleString() + ' bytes)';
      }
    }

Like so:

![behind-image-size-demo](https://user-images.githubusercontent.com/8264646/119542240-29b3b100-bd44-11eb-9e8d-4e000819afd9.png)

**Comment by kubuzetto** [comment]
Thank you for the bug report! I wanted to see the feasibility of this before responding to the issue, and I ran a few tests with the Performance API (thank you very much for the suggestion @jscher2000).

Unfortunately, there is a recurring case where the `getEntriesByName` call returns an empty array. Strangely, refreshing the inline page returns the proper results.

At first I thought it was a race condition, maybe I was requesting the data before it was set. Adding a `PerformanceObserver` in the mix did not help. I periodically polled the whole entry list with `getEntries` instead, and saw that the relevant `PerformanceResourceTiming` entries are never registered.

For now, I can't get it to work reliably. I will keep looking into this.

**Comment by kubuzetto** [comment]
(If anybody else is interested in looking into this, you can replicate this problem with the main Google logo in the [Google main page](http://www.google.com))

**Comment by jscher2000** [comment]
Hmm, bummer. I have some elaborate code to bypass the cache, which might be why I can get the value.

* Adding unique URL parameter: https://github.com/jscher2000/View-Image-Info-Reborn-for-Firefox/blob/main/view-image-info-page.js#L175
* Intercepting and cleaning so it isn't sent to the server: https://github.com/jscher2000/View-Image-Info-Reborn-for-Firefox/blob/main/view-image-info-webrequest.js#L121

That might be more trouble than it's worth.

**Comment by kubuzetto** [comment]
Closing this issue, since I was unable to find a reliable method for this.
