### ISSUE TITLE
Download zoomable images/split in titles

### ISSUE THREAD

**Issue by eadmaster** [kubuzetto/behind#16]
use case: [Google Arts & Culture](https://www.reddit.com/r/web_design/comments/ap68dl/google_arts_culture_paintings_download/)

**Comment by kubuzetto** [comment]
Thanks for the suggestion @eadmaster, and sorry for the late answer. That is rather out-of-scope for this extension, but I can recommend dezoomify for that task: https://addons.mozilla.org/en-US/firefox/addon/dezoomify/
