### ISSUE TITLE
DoS against sites possible by repeated requests when 404s are returned

### ISSUE THREAD

**Issue by s1shed** [kubuzetto/behind#22]
A popular retail site has an img tag like the following:

```
<img alt="Picture 2" sizes="(min-width: 1280px) 816px, (min-width: 1024px) 62vw, 100vw" srcset="https://site.tld/image/w=375,h=234,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 375w, https://site.tld/image/w=568,h=355,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 568w, https://site.tld/image/w=750,h=469,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 750w, https://site.tld/image/w=816,h=510,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 816w, https://site.tld/image/w=1125,h=703,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 1125w, https://site.tld/image/w=1632,h=1020,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 1632w, https://site.tld/image/w=2448,h=1530,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg 2448w" loading="lazy" src="https://site.tld/image/w=375,h=234,fit=scale-down,q=75,f=auto,sharpen=0.5/images/5/2_1-1440x712.jpeg" width="375" height="234">
```

The Behind addon attempts to download images with names like `w=2448`, `h=1020`, etc. Additional examples below:

![behind window](https://user-images.githubusercontent.com/8793762/158062340-d47ff0eb-1e5f-4474-80a8-b646d6266276.png)

These requests receive a 404 response, which is to be expected from the `srcset` above.  

![404s shown in network tab](https://user-images.githubusercontent.com/8793762/158062398-eb8256a9-bb88-4416-9e43-1125a40f37b6.png)

Unfortunately these requests are made repeatedly—and frequently—effectively leading to a DoS against the site. If this tab is left open for a few hours several gigabytes of traffic can easily be generated, unbeknownst to the addon user. 

The requests are not logged to the browser history so this was discovered by looking in the Network tab of the developer tools while Behind was active on an affected site.

**Comment by kubuzetto** [comment]
Hi @s1shed, thank you very much for the bug report!

I prepared [a fix that probably resolves this](https://github.com/kubuzetto/behind/pull/23); but I cannot try it, given that I have no way of replicating the situation.

Would you be willing to test the PR on the same retail page, to see if it fixes the issue?

**Comment by kubuzetto** [comment]
Oh nevermind lol, I just stumbled upon that same bug! Tested it and it seems to work fine. Version 0.2.18 with the fix should be available in a few minutes.

**Comment by kubuzetto** [comment]
The new version is available for Firefox, and in review for Chrome. Closing the issue, thanks again!

**Comment by elfshed** [comment]
> The new version is available for Firefox, and in review for Chrome. Closing the issue, thanks again!

Thanks for the quick fix! I  verified with the site I saw this on.
