### ISSUE TITLE
Option to automatically go to the largest image when there multiple images on the same area

### ISSUE THREAD

**Issue by ericpa06** [kubuzetto/behind#25]
I would like to ask if it would be possible to add an option that makes the extension to automatically select the image with bigger/largest/wildest/tallest resolution (depending on the users preferences) when there are multiple images on a same area. Like this for instance:

![image](https://user-images.githubusercontent.com/6937720/161347800-5be87a3b-de2a-4411-9fea-2e72f357eee1.png)

Thank you very much.

**Comment by kubuzetto** [comment]
Thank you for the suggestion @ericpa06 !

There is a setting for opening the image when there is only one result; maybe I can combine the two behaviors. I'll be looking into it, next week earliest (busy week at work). Meanwhile I'll also tag this as a good first issue, if anybody else wants to try it as well.

**Comment by HamedEmine** [comment]
I was looking for this specific feature in the settings! I hope you add it very soon!

**Comment by kubuzetto** [comment]
I just released version 0.2.20 with this feature included, thank you both @ericpa06 @HamedEmine !

I ran some tests and encountered no problems, but hopefully it works everywhere :)
