### ISSUE TITLE
Waterfox

### ISSUE THREAD

**Issue by PiliJ** [kubuzetto/behind#3]
The option of the right-click context menu don't appear in Waterfox Classic last version...

**Comment by kubuzetto** [comment]
Thanks for the bug report!

Upon first inspection, the `"visible": false` setting in the `contextMenus.create` call seems to be causing the problem. I suspect that Waterfox does not support this flag, but does not play along with extra fields in the properties either. I'll look into it when I get home from work.

Add-on works as expected with Waterfox Current.

**Comment by kubuzetto** [comment]
As suspected, `"visible": false` is causing the problem. I applied some weird workaround there: in Waterfox, context menu icon is never hidden now. But at least it works :)

**Comment by PiliJ** [comment]
Thank you kubuzetto.
Have you see the post on Ghacks ?
https://www.ghacks.net/2020/07/04/firefox-add-on-behind-lets-you-download-any-image-that-is-behind-the-cursor/

**Comment by kubuzetto** [comment]
Happy to help :)

Yes, I saw it when u/UltraExelon shared the post on r/Firefox. It's an insane feeling to stumble upon a post about your own add-on 😄
