### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by TeardropOmen** [kubuzetto/behind#5]
The background should be a dark color when the browser is set to a dark theme.

**Comment by kubuzetto** [comment]
I'll look into this. I don't yet know if the browser exposes this information to addons (AFAIK you can sometimes get the system preference for dark themes, but it could have been disabled by the user to prevent fingerprinting).

As a fallback, would a checkbox in the Options page (that you would have to manually enable) do the job?

**Comment by TeardropOmen** [comment]
I think it could be done using the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) CSS media feature.

An additional manual override in the options for users with anti-fingerprinting would be a good idea, giving users the choice between automatic, light or dark theme.

**Comment by shesharp1011** [comment]
this feature is now available in v0.2.6

**Comment by kubuzetto** [comment]
Thank you @shesharp1011 for the contribution :) closing the issue
