### ISSUE TITLE
discuss.com.hk

### ISSUE THREAD

**Issue by mkeroppi** [kubuzetto/behind#6]
Does not seem to work for images in the main box on this page: https://www.discuss.com.hk/

**Comment by kubuzetto** [comment]
Can verify; the content menu was visible for neither the header nor the content. I will try to look into this tonight.

**Comment by kubuzetto** [comment]
Huh, weird. Allowing the add-on to work on private windows made it work on the page. Can you please try the following steps?

- Go to about:addons
- Click on "behind!"
- Under "Details", set "Run in Private Windows" to "Allow"
- Go to discuss.com.hk
- Right click on an image in the content (not header; the only actual image in the header is the facebook icon)

**Comment by mkeroppi** [comment]
The images in the screenshot attached cannot be captured using the extension.

![Screenshot_2020-10-12 香港討論區(1)](https://user-images.githubusercontent.com/35188272/95810256-c356b280-0ccd-11eb-9f71-d668497a5218.png)

**Comment by kubuzetto** [comment]
Ok, just to be on the same page - is this the behavior you're observing?

- On right-click, "behind" content menu appears
- When you click on it, the link seems broken and the image cannot be downloaded

![ss](https://user-images.githubusercontent.com/9467143/95823347-1cf2c780-0d36-11eb-8d17-b5a9158e640c.png)

**Comment by mkeroppi** [comment]
> 
> 
> Ok, just to be on the same page - is this the behavior you're observing?
> 
>     * On right-click, "behind" content menu appears
> 
>     * When you click on it, the link seems broken and the image cannot be downloaded
> 
> 
> ![ss](https://user-images.githubusercontent.com/9467143/95823347-1cf2c780-0d36-11eb-8d17-b5a9158e640c.png)

Yes.  That is exactly correct.

**Comment by kubuzetto** [comment]
Ok here's one of the problematic URLs:
`background-image:url('https://cdn.discuss.com.hk/t/3c2710/f/320x320/filters:extract_cover()/https://img.discuss.com.hk/d/attachments/day_201011/20201011_0e4f118b79b726be1169UXilRwXQknXp.jpg');`
The regex I use for matching the URLs think that this part is the URL:
_`background-image:url(`_ **`'https://cdn.discuss.com.hk/t/3c2710/f/320x320/filters:extract_cover(`** _`)`_
so obviously it cannot show the image afterwards.
I will try to come up with a better regex for this. Will release this as version 0.2.9 when I do. Thanks for the bug report!

**Comment by mkeroppi** [comment]
That make sense now.  Cross referenced to a long time bug in another extension.  Thanks!

**Comment by kubuzetto** [comment]
0.2.9 includes the fix; the problem seems to be solved. Thanks :)
