### ISSUE TITLE
Open image in view mode (suggestion)

### ISSUE THREAD

**Issue by happysurf** [kubuzetto/behind#8]
I use the great Viewhance extension for view the images in Firefox, for that will be great add an option like this:

- When the user make click on image inside behind:
1. Save image;
2. Enter in Firefox view image mode (in my case with Viewhance).
3. View image in behind, like now.

Otherwise all the times with mouse right click  I must select > View Image.

Thanks.

**Comment by kubuzetto** [comment]
Unfortunately; different kinds of images that _behind!_ supports (including [Data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs), vector images and so forth) make it difficult to view as image, as some of them may be embedded within the DOM. Furthermore, some of these scenarios cannot be opened in a new tab as a URL (scripts are prevented from doing it by Firefox as a security measure). You can view individual images that _behind!_ shows by left-clicking on them, but that does not open the native image preview screen of the browser; instead an extension page _imitating_ the native image preview window will be opened. This is the reason.

It might be possible to blacklist these cases but I'm not exactly a proponent of it; as different kinds of URLs would require the user to act differently, with no feedback to the user whatsoever.

I know it's not exactly the same thing but there is an option to open one-result images directly, you can enable it in the preferences.
