### ISSUE TITLE
Images listed in size order (suggestion)

### ISSUE THREAD

**Issue by happysurf** [kubuzetto/behind#9]
Will be great have the images result in size order (from small to bigger or reversal), because sometimes there are many images listed in behind, for that is not easy found immediately the biggest (in my case).

Example: https://simonhaiduk.com/products/synergenesis

In this case there are 6 images with similar size but not in order.

**Comment by kubuzetto** [comment]
I also think that this is a critical feature for usability. One problem is that the image sizes are determined after the images are fully loaded, so in slow connections this might cause images to abruptly re-order. Maybe I can somehow highlight the biggest image in the page as a workaround. Will think about it, thanks!

**Comment by kubuzetto** [comment]
This feature is now available in version 0.2.12.
